# Generated by Django 5.1.7 on 2025-03-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('año_lanzamiento', models.PositiveIntegerField(verbose_name='Año de lanzamiento')),
                ('genero', models.CharField(choices=[('ACC', 'Acción'), ('COM', 'Comedia'), ('DRA', 'Drama'), ('TER', 'Terror'), ('SCI', 'Ciencia ficción'), ('ANI', 'Animación'), ('ROM', 'Romance'), ('DOC', 'Documental')], max_length=3, verbose_name='Género')),
                ('duracion', models.PositiveIntegerField(help_text='Duración en minutos', verbose_name='Duración (minutos)')),
                ('director', models.CharField(max_length=100, verbose_name='Director')),
                ('calificacion', models.DecimalField(decimal_places=1, help_text='Calificación de 0.0 a 10.0', max_digits=3, verbose_name='Calificación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/', verbose_name='Portada')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
